/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitquill_ocr_GrayImage */

#ifndef _Included_net_bitquill_ocr_GrayImage
#define _Included_net_bitquill_ocr_GrayImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeMeanFilter
 * Signature: ([B[BIII)I
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_GrayImage_nativeMeanFilter
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeMean0
 * Signature: ([BII)F
 */
JNIEXPORT jfloat JNICALL Java_net_bitquill_ocr_GrayImage_nativeMean0
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeVariance0
 * Signature: ([BII)F
 */
JNIEXPORT jfloat JNICALL Java_net_bitquill_ocr_GrayImage_nativeVariance0
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeMean
 * Signature: ([BIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_net_bitquill_ocr_GrayImage_nativeMean
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeVariance
 * Signature: ([BIIIIII)F
 */
JNIEXPORT jfloat JNICALL Java_net_bitquill_ocr_GrayImage_nativeVariance
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeHistogram
 * Signature: ([BII[I)V
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_GrayImage_nativeHistogram
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeGrayToARGB
 * Signature: ([BII[IIII)V
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_GrayImage_nativeGrayToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray, jint, jint, jint, jint);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeAdaptiveThreshold
 * Signature: ([B[B[BIIBBI)V
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_GrayImage_nativeAdaptiveThreshold
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jint, jbyte, jbyte, jint);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeErode
 * Signature: ([B[BIII[I[I[IIIII)V
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_GrayImage_nativeErode
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint,
        jint, jintArray, jintArray, jintArray, jint, jint, jint, jint);

/*
 * Class:     net_bitquill_ocr_GrayImage
 * Method:    nativeDilate
 * Signature: ([B[BIII[I[I[IIIII)V
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_GrayImage_nativeDilate
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint,
        jint, jintArray, jintArray, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
