/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitquill_ocr_Decoder */

#ifndef _Included_net_bitquill_ocr_Decoder
#define _Included_net_bitquill_ocr_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitquill_ocr_Decoder
 * Method:    nativeNaiveMeanFilter
 * Signature: ([B[BIII)B
 */
JNIEXPORT jint JNICALL Java_net_bitquill_ocr_Decoder_nativeNaiveMeanFilter
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     net_bitquill_ocr_Decoder
 * Method:    nativeMeanFilter1
 * Signature: ([B[BIII)B
 */
JNIEXPORT jint JNICALL Java_net_bitquill_ocr_Decoder_nativeMeanFilter1
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
