/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_bitquill_ocr_Decoder */

#ifndef _Included_net_bitquill_ocr_Decoder
#define _Included_net_bitquill_ocr_Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bitquill_ocr_PreviewImage
 * Method:    nativeMeanFilter
 * Signature: ([B[BIII)I
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_PreviewImage_nativeMeanFilter
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint);

/*
 * Class:     net_bitquill_ocr_PreviewImage
 * Method:    nativeMean
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_net_bitquill_ocr_PreviewImage_nativeMean
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     net_bitquill_ocr_PreviewImage
 * Method:    nativeGrayToARGB
 * Signature: ([BII[IIII)V
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_PreviewImage_nativeGrayToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray, jint, jint, jint, jint);

/*
 * Class:     net_bitquill_ocr_PreviewImage
 * Method:    nativeAdaptiveThreshold
 * Signature: ([B[B[BIIBBI)V
 */
JNIEXPORT void JNICALL Java_net_bitquill_ocr_PreviewImage_nativeAdaptiveThreshold
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jint, jbyte, jbyte, jint);

#ifdef __cplusplus
}
#endif
#endif
